tap "apenngrace/vulkan"
tap "daipeihust/tap"
tap "homebrew/bundle"
brew "cask"
brew "cmake"
brew "colordiff"
brew "gibo"
brew "git-lfs"
brew "glfw"
brew "goenv"
brew "hub"
brew "mas"
brew "mysql"
brew "node-build"
brew "nodenv"
brew "pipenv"
brew "pyenv"
brew "rbenv"
brew "tree"
brew "wget"
brew "daipeihust/tap/im-select"
cask "adobe-creative-cloud"
cask "alfred"
cask "bettertouchtool"
cask "blender"
cask "clipy"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "keycastr"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "microsoft-teams"
cask "obs"
cask "rider"
cask "slack"
cask "sublime-text"
cask "unity-hub"
cask "visual-studio-code"
cask "zoom"
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
mas "QuickShade", id: 931571202
